src/Entity/Traits/FileTrait.php
<?php


namespace App\Entity\Traits;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File as HttpFile;
use Symfony\Component\HttpFoundation\File\MimeType\ExtensionGuesser;
use Symfony\Component\HttpFoundation\File\UploadedFile as HttpUploadedFile;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Gedmo\Blameable\Traits\BlameableEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;

trait FileTrait
{
    use BlameableEntity;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @var integer
     *
     * @ORM\Column(type="integer")
     *
     * @Assert\NotBlank()
     * @Assert\Type(type="integer")
     * @Assert\GreaterThan(value=0)
     */
    private $size;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     *
     * @Assert\NotBlank()
     * @Assert\Type(type="string")
     */
    private $mime;

    public function __construct(HttpFile $file = null)
    {
        $this->setFile($file);
    }

    /**
     * @return HttpFile
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * @param HttpFile|null $file
     * @return $this
     * @throws \Exception
     */
    public function setFile(HttpFile $file = null)
    {
        $this->file = $file;

        if ($file && file_exists($file->getPathname())) {
            $this->updatedAt = new \DateTime('now');
            $this->size      = (!$file instanceof HttpUploadedFile) ? $file->getSize() : $file->getClientSize();
            $this->mime      = (!$file instanceof HttpUploadedFile) ? $file->getMimeType() : $file->getClientMimeType();
        }

        return $this;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return $this
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return int
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * @param int $size
     * @return $this
     */
    public function setSize($size)
    {
        $this->size = $size;

        return $this;
    }

    /**
     * @return string
     */
    public function getMime()
    {
        return $this->mime;
    }

    /**
     * @return string
     */
    public function getExtension()
    {
        return ExtensionGuesser::getInstance()->guess($this->mime);
    }
}

templates/admin_base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    {% block stylesheets %}

    <link href="{{ asset('admin/assets/libs/flot/css/float-chart.css')}}" rel="stylesheet">

    <link href="{{ asset('admin/dist/css/style.min.css')}}" rel="stylesheet">

    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>

    <link href="{{ asset('admin/assets/libs/flot/css/float-chart.css')}}" rel="stylesheet">

    <link href="{{ asset('admin//dist/css/style.min.css')}}" rel="stylesheet">
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    {% endblock %}
</head>
<body>
    <div id="main-wrapper">
        {% include 'admin/partial/_header.html.twig' %}
        {% include 'admin/partial/_sider.html.twig' %}
        <div class="page-wrapper">
            {% block body %} {% endblock %}
        </div>
    </div>
{% block javascripts %}


    <!-- Js Plugins -->
    <script src="{{ asset('template/js/jquery-3.3.1.min.js') }}"></script>
    <script src="{{ asset('template/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('template/js/jquery.magnific-popup.min.js') }}"></script>
    <script src="{{ asset('template/js/jquery-ui.min.js') }}"></script>
    <script src="{{ asset('template/js/jquery.nice-select.min.js') }}"></script>
    <script src="{{ asset('template/js/jquery.slicknav.js') }}"></script>
    <script src="{{ asset('template/js/owl.carousel.min.js') }}"></script>
    <script src="{{ asset('template/js/main.js') }}"></script>

{% endblock %}
</body>
</html>

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
            <title>Mega Drvo doo</title>

            <!--Favicon-->
            <link rel="icon" href="{{ asset('template/favicon/mega-drvo-72x72.png')}}" type="image/gif" sizes="36x36">
            <!-- <link rel="apple-touch-icon" sizes="60x60" href="favicon/apple-icon-60x60.png">
            <link rel="apple-touch-icon" sizes="72x72" href="favicon/apple-icon-72x72.png">
            <link rel="apple-touch-icon" sizes="76x76" href="favicon/apple-icon-76x76.png">
            <link rel="apple-touch-icon" sizes="114x114" href="favicon/apple-icon-114x114.png">
            <link rel="apple-touch-icon" sizes="120x120" href="favicon/apple-icon-120x120.png">
            <link rel="apple-touch-icon" sizes="144x144" href="favicon/apple-icon-144x144.png">
            <link rel="apple-touch-icon" sizes="152x152" href="favicon/apple-icon-152x152.png">
            <link rel="apple-touch-icon" sizes="180x180" href="favicon/apple-icon-180x180.png">
            <link rel="icon" type="image/png" sizes="192x192"  href="favicon/android-icon-192x192.png">
            <link rel="icon" type="image/png" sizes="32x32" href="favicon/favicon-32x32.png">
            <link rel="icon" type="image/png" sizes="96x96" href="favicon/favicon-96x96.png">
            <link rel="icon" type="image/png" sizes="16x16" href="favicon/favicon-16x16.png">
            <link rel="manifest" href="favicon/manifest.json">
            <meta name="msapplication-TileColor" content="#ffffff">
            <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
            <meta name="theme-color" content="#ffffff"> -->

            <!--    fonts-->
            <!-- <link href='https://fonts.googleapis.com/css?family=Raleway:800,700,500,400,600' rel='stylesheet' type='text/css'>
            <link href='https://fonts.googleapis.com/css?family=Lato:400,300,700,300italic' rel='stylesheet' type='text/css'>
            <link href='https://fonts.googleapis.com/css?family=PT+Serif:400,400italic,700' rel='stylesheet' type='text/css'>

            <link href='https://fonts.googleapis.com/css?family=Alegreya:400,700,700italic,400italic' rel='stylesheet' type='text/css'>
            <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'> -->

            <!-- Bootstrap -->
            <link href="{{ asset('template/css/bootstrap.min.css')}}" rel="stylesheet">
            <link href="{{ asset('template/css/bootstrap-theme.min.css')}}" rel="stylesheet">
            <link href="{{ asset('template/css/font-awesome.min.css')}}" rel="stylesheet">
            <link href="{{ asset('template/css/strock-icon.css')}}" rel="stylesheet">
            <!--    owl-carousel-->
            <link rel="stylesheet" href="{{ asset('template/vendors/owlcarousel/owl.carousel.css')}}">
            <link href="{{ asset('template/vendors/rs-plugin/css/settings.css')}}" rel="stylesheet">
            <link href="{{ asset('template/vendors/magnific/magnific-popup.css')}}" rel="stylesheet">
            <!--    css-->
            <link rel="stylesheet" href="{{ asset('template/css/style.css')}}">









{#            #}
{#            <!-- Google Font -->#}
{#            <link href="https://fonts.googleapis.com/css?family=Taviraj:300,400,500,600,700,800,900&display=swap"#}
{#                  rel="stylesheet">#}
{#            <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800&display=swap" rel="stylesheet">#}

{#            <!-- Css Styles -->#}
{#            <link rel="stylesheet" href="{{ asset('template/css/bootstrap.min.css')}}" type="text/css">#}
{#            <link rel="stylesheet" href="{{ asset('template/css/font-awesome.min.css')}}" type="text/css">#}
{#            <link rel="stylesheet" href="{{ asset('template/css/flaticon.css')}}" type="text/css">#}
{#            <link rel="stylesheet" href="{{ asset('template/css/linearicons.css')}}" type="text/css">#}
{#            <link rel="stylesheet" href="{{ asset('template/css/owl.carousel.min.css')}}" type="text/css">#}
{#            <link rel="stylesheet" href="{{ asset('template/css/jquery-ui.min.css')}}" type="text/css">#}
{#            <link rel="stylesheet" href="{{ asset('template/css/nice-select.css')}}" type="text/css">#}
{#            <link rel="stylesheet" href="{{ asset('template/css/magnific-popup.css')}}" type="text/css">#}
{#            <link rel="stylesheet" href="{{ asset('template/css/slicknav.min.css')}}" type="text/css">#}
{#            <link rel="stylesheet" href="{{ asset('template/css/style.css')}}" type="text/css">#}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}

            <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
            <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
            <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
            <![endif]-->

            <script src="{{ asset('template/js/jquery-2.2.0.min.js')}}"></script>
            <script src="{{ asset('template/js/bootstrap.min.js')}}"></script>
            <!--RS-->
            <script src="{{ asset('template/vendors/rs-plugin/js/jquery.themepunch.tools.min.js')}}"></script> <!-- Revolution Slider Tools -->
            <script src="{{ asset('template/vendors/rs-plugin/js/jquery.themepunch.revolution.min.js')}}"></script> <!-- Revolution Slider -->
            <script src="{{ asset('template/vendors/rs-plugin/js/extensions/revolution.extension.actions.min.js')}}"></script>
            <script src="{{ asset('template/vendors/rs-plugin/js/extensions/revolution.extension.carousel.min.js')}}"></script>
            <script src="{{ asset('template/vendors/rs-plugin/js/extensions/revolution.extension.kenburn.min.js')}}"></script>
            <script src="{{ asset('template/vendors/rs-plugin/js/extensions/revolution.extension.layeranimation.min.js')}}"></script>
            <script src="{{ asset('template/vendors/rs-plugin/js/extensions/revolution.extension.migration.min.js')}}"></script>
            <script src="{{ asset('template/vendors/rs-plugin/js/extensions/revolution.extension.navigation.min.js')}}"></script>
            <script src="{{ asset('template/vendors/rs-plugin/js/extensions/revolution.extension.parallax.min.js')}}"></script>
            <script src="{{ asset('template/vendors/rs-plugin/js/extensions/revolution.extension.slideanims.min.js')}}"></script>
            <script src="{{ asset('template/vendors/rs-plugin/js/extensions/revolution.extension.video.min.js')}}"></script>

            <script src="{{ asset('template/vendors/isotope/isotope.min.js')}}"></script>
            <script src="{{ asset('template/vendors/imagesloaded/imagesloaded.pkgd.min.js')}}"></script>
            <script src="{{ asset('template/vendors/owlcarousel/owl.carousel.min.js')}}"></script>
            <script src="{{ asset('template/vendors/magnific/jquery.magnific-popup.min.js')}}"></script>
            <script src="{{ asset('template/js/theme.js')}}"></script>


{#            <!-- Js Plugins -->#}
{#            <script src="{{ asset('template/js/jquery-3.3.1.min.js') }}"></script>#}
{#            <script src="{{ asset('template/js/bootstrap.min.js') }}"></script>#}
{#            <script src="{{ asset('template/js/jquery.magnific-popup.min.js') }}"></script>#}
{#            <script src="{{ asset('template/js/jquery-ui.min.js') }}"></script>#}
{#            <script src="{{ asset('template/js/jquery.nice-select.min.js') }}"></script>#}
{#            <script src="{{ asset('template/js/jquery.slicknav.js') }}"></script>#}
{#            <script src="{{ asset('template/js/owl.carousel.min.js') }}"></script>#}
{#            <script src="{{ asset('template/js/main.js') }}"></script>#}

        {% endblock %}
    </body>
</html>